version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=${SERVER_DB_USERNAME}
      - POSTGRES_PASSWORD=${SERVER_DB_PASSWORD}
      - POSTGRES_DB=home_server
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${SERVER_DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${SERVER_DB_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin

volumes:
  postgres_data:
  pgadmin_data: